name: Upload to EC2

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Composer
        uses: php-actions/composer@v6
        with:
          dev: no
      
      - name: 'Create env file'
        run: |
          touch .env
          echo EC2_HOST="${{ secrets.EC2_HOST }}" >> .env
          echo EC2_USER=${{ secrets.EC2_USER }} >> .env
          cat .env
        
      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          TARGET: /var/www/git_test/
